fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive: "git://github.com/voxpupuli/puppet-archive.git"
    file_capability: "git://github.com/smoeding/puppet-file_capability.git"
  symlinks:
    vault: "#{source_dir}"
